#version 430
layout ( binding = 0, rgba32f ) readonly uniform image2D inImg;
layout ( binding = 1, rgba32f ) writeonly uniform image2D outImg;

layout (local_size_x = 32, local_size_y = 32) in;
void main() {

	ivec2 index = ivec2 (gl_GlobalInvocationID.xy);
	
	vec4 texel_color = imageLoad(inImg, index);
	
	vec4 resulting_color = vec4(1.0 - texel_color.rgb, texel_color.a);
	
	imageStore(outImg, index, resulting_color);
	
}