#SET(KINECTSDK_ROOT_DIR "c:/Program Files/Microsoft SDKs/Kinect/v1.0/")
IF(DEFINED ENV{KINECTSDK_ROOT})
SET(KINECTSDK_ROOT "$ENV{KINECTSDK_ROOT}")
ENDIF()
SET(KINECTSDK_ROOT
		"${KINECTSDK_ROOT}"
		CACHE
		PATH
		"Root directory to search for KinectSDK")

#message(${KINECTSDK_ROOT_DIR})
#SET(KINECT_SDK_LIB_DIR "${KINECTSDK_ROOT_DIR}/Lib/x86/")
FIND_PATH(KINECT_SDK_INCLUDE_DIR Kinect.h 
	${KINECTSDK_ROOT}/inc
	${KINECTSDK_ROOT}
	)

	
	SET(KINECT_SDK_DLLS 
	$ENV{SystemRoot}System32/Kinect20.dll
)

# IF (DEFINED ENV{KINECTSDK_ROOT_DIR})
   # SET(KINECTSDK_ROOT_DIR "${KINECTSDK_ROOT}")
# ENDIF()
# SET(KINECTSDK_ROOT
    # "${KINECTSDK_ROOT}"
    # "Root directory to search for KinectSDK")


SET(KINECT_SDK_INCLUDES 
	${KINECTSDK_ROOT}/inc

)
FIND_LIBRARY(KINECT_SDK_LIBRARY 
	NAMES Kinect20
	PATHS ${KINECTSDK_ROOT}/Lib/x86
)

#MARK_AS_ADVANCED(KINECT_SDK_LIBRARY)
# MARK_AS_ADVANCED(KINECT_SDK_LIBRARY_DEBUG)


# ####################   Macro   #######################
# MACRO(CHECK_FILES _FILES _DIR)
	# SET(_MISSING_FILES)
	# FOREACH(_FILE ${${_FILES}})
		# IF(NOT EXISTS "${_FILE}")
			# SET(KINECT_SDK_FOUND NO)
			# get_filename_component(_FILE ${_FILE} NAME)
			# SET(_MISSING_FILES "${_MISSING_FILES}${_FILE}, ")
		# ENDIF()
	# ENDFOREACH()
	# IF(_MISSING_FILES)
		# MESSAGE(STATUS "In folder \"${${_DIR}}\" not found files: ${_MISSING_FILES}")
		# SET(KINECT_SDK_FOUND NO)
	# ENDIF()
# ENDMACRO(CHECK_FILES)

# MACRO(CHECK_DIR _DIR)
	# IF(NOT EXISTS "${${_DIR}}")
		# MESSAGE(STATUS "Folder \"${${_DIR}}\" not found.")
		# SET(KINECT_SDK_FOUND NO)
	# ENDIF()
# ENDMACRO(CHECK_DIR)

# ##################### Checking #######################
# MESSAGE(STATUS "Searching KINECT_SDK.")
# SET(KINECT_SDK_FOUND YES)

# CHECK_DIR(KINECTSDK_ROOT_DIR)
# IF(KINECT_SDK_FOUND)
	# CHECK_DIR(KINECT_SDK_LIB_DIR)
	# CHECK_DIR(KINECT_SDK_INCLUDE_DIR)
	
	# IF(KINECT_SDK_FOUND)
		# #CHECK_FILES(KINECT_SDK_DLLS KINECTSDK_ROOT_DIR)
		# CHECK_FILES(KINECT_SDK_LIBRARIES KINECT_SDK_LIB_DIR)
		# CHECK_FILES(KINECT_SDK_INCLUDES KINECT_SDK_INCLUDE_DIR)
	# ENDIF()
# ENDIF()

# MESSAGE(STATUS "KINECT_SDK_FOUND - ${KINECT_SDK_FOUND}.")