FIND_PACKAGE(GTK3)

IF (DEFINED ENV{GTK3_ROOT})
    SET(GTK3_ROOT "$ENV{GTK3_ROOT}")
ENDIF()
SET(GTK3_ROOT
    "${GTK3_ROOT}"
    CACHE
    PATH
    "Root directory to search for GTK3")

FIND_PATH( GTK3_INCLUDE_DIR
    NAMES
        gtk-3.0/gtk.h
    PATHS
        ${GTK3_SEARCH_PATHS}
    PATH_SUFFIXES
       

IF(GTK3_FOUND)
   INCLUDE_DIRECTORIES(${GTK3_INCLUDE_DIR})
ENDIF(GTK_FOUND)
