/*
* Texture that is purely generated by converting a string to an image
*/
#pragma once

#include <GL\glew.h>
#include "ShaderTools\VertexArrayObject.h"
#include "cairo\cairo.h"
#include "gtk\gtk.h"
#include <string>

class TextTexture
{
public:
	TextTexture(int textureWidth, int textureHeight, const char *string, const GdkRGBA& textColor, const GdkRGBA& background, int fontSize);
	virtual ~TextTexture();
	
	GLuint getTextureHandle();


private:
	GLuint			m_textureId;
	int				m_width;
	int				m_height;
	int				m_fontSize;
	std::string		m_string;
	GdkRGBA			m_textColor;
	GdkRGBA			m_backgroundColor;

	void initTexture();
	void updateTextureData(unsigned char* data);
	cairo_t* createCairoContext(int textureWidth, int textureHeight, int channels, cairo_surface_t** surf, unsigned char** buffer);
	int drawText();
	
};

