#version 430
layout ( rgba16f, binding = 0 ) uniform image2D outTexture;
layout ( rgba16f, binding = 2 ) uniform image2D positionTexture;

uniform mat4 mvpOld;
uniform mat4 mvpNew;

layout (local_size_x = 16, local_size_y = 16) in;
void main() {
    ivec2 inCoord = ivec2(gl_GlobalInvocationID.xy);
    vec4 wPos = imageLoad(positionTexture, inCoord);
    vec4 iPos = mvpNew * vec4(wPos.xyz,1);
    iPos /= iPos.w;
    vec2 coordColor = vec2(
        float(float(inCoord.x) / " + w + ".0),
        float(float(inCoord.y) / " + h + ".0));
    ivec2 outCoord = ivec2(
        float(iPos.x + 1.0) * 0.5 * " + h + ".0 + (" + w + ".0-" + h + ".0)/2.0,
        float(iPos.y + 1.0) * 0.5 * " + h + ".0);
    vec4 lastIteration;
    ivec2 tmp;
    tmp = outCoord;
    lastIteration = imageLoad(outTexture, tmp);
    if (lastIteration.z > iPos.z) {
        imageStore(outTexture, tmp, vec4(coordColor, iPos.z, 1.0));
    }
}